name: 'ethiopian_medical_analytics'
version: '1.0.0'
config-version: 2

profile: 'ethiopian_medical_analytics'

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
analysis-paths: ["analyses"]

target-path: "target"
clean-targets: ["target"]

models:
  ethiopian_medical_analytics:
    staging:
      +schema: staging
    marts:
      +schema: analytics